### PR TITLE
Make http instrumentation use req.emit instead of response event handler

### LINKED ISSUE #248: Auto breadcrumbs HTTP causes DynamoDB errors in AWS Lambda environments
I tried using `autoBreadcrumbs: true` in an AWS Lambda function, but when deployed to AWS all my DynamoDB operations started failing with `Error: CRC32CheckFailed: CRC32 integrity check failed` errors.

The errors went away after changing my Raven config to `autoBreadcrumbs: { console: true }`.

### PR DESCRIPTION
**Pull request by LewisJEllis**
Should fix #248 and #273. Now our instrumentation for http breadcrumbs will pick up response details via monkeypatching `ClientRequest.emit` and watching the `response` event, rather than just adding a listener for the `response` event (which then forces us to sort-of-consume the response body to avoid eating memory, which then interacts poorly with at least aws-sdk). Went down a few of rabbit holes on this but it turned out to be pretty straightforward in the end.

I upgraded our should.js devdep while trying to make a test fail more nicely, but it didn't help and I decided I don't care about tests failing nicely since they're meant to pass; left it since it also revealed a small inconsistency in our tests.

/cc @MaxBittker @benvinegar @ide

### CODE REVIEW

File: lib/breadcrumbs.js [hunk 1]
```diff
@@ -87,21 +87,22 @@ var wrappers = {
...
+                  url: url,
+                  status_code: maybeResp.statusCode
+                }
+              });
             }
-          });
-
-          // No-op to consume response data since we added a response handler
-          // see https://nodejs.org/api/http.html#http_class_http_clientrequest
-          response.on('data', function () {});
```
Comment (LewisJEllis) [inline lib/breadcrumbs.js]: This `data` listener was causing `_readableState.flowing` to be true; see https://nodejs.org/api/stream.html#stream_three_states

**Comment by LewisJEllis** [comment]
Whoops, meant to reference #273.
